"""empty message

Revision ID: 1e3214222e50
Revises: 37ea8dccf487
Create Date: 2023-11-09 09:49:17.353661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3214222e50'
down_revision = '37ea8dccf487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarifa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tarifas', ['tarifa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tarifa_id')

    # ### end Alembic commands ###
