"""empty message

Revision ID: 37ea8dccf487
Revises: 89422992ffbd
Create Date: 2023-11-08 21:41:23.842261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37ea8dccf487'
down_revision = '89422992ffbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celdas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_celda', sa.String(length=50), nullable=False))
        batch_op.drop_index('numero')
        batch_op.create_unique_constraint(None, ['ubicacion_celda'])
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celdas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('numero', ['numero'], unique=False)
        batch_op.drop_column('ubicacion_celda')

    # ### end Alembic commands ###
