"""empty message

Revision ID: 79f6c3b2d6ae
Revises: 457cb6a71a1c
Create Date: 2023-11-05 08:48:10.607998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79f6c3b2d6ae'
down_revision = '457cb6a71a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('usuarios_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuarios_ibfk_1', 'roles', ['role_id'], ['id'])
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###
